export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SELECT_GENRES = 'SELECT_GENRES';